import {IDeck} from '../types/deck.types';
import {ICardList} from '../types/card.types.ts';

// Initial decks configuration
export const INITIAL_DECKS: IDeck[] = [
  {
    id: 'default-deck-1',
    topic: 'Polish Common Phrases',
    description: 'Essential Polish phrases for everyday conversation',
    languageFrom: 'Polish',
    languageTo: 'English',
    amount: 30,
    promptToAiAgent:
      'Please create JSON with Polish common phrases and their English translations, including pronunciation and remarks for context.',
  },
  {
    id: 'default-deck-2',
    topic: 'Spanish Basic Vocabulary',
    description: 'Essential Spanish words for beginners',
    languageFrom: 'Spanish',
    languageTo: 'English',
    amount: 20,
    promptToAiAgent:
      'Please create JSON with basic Spanish vocabulary words and their English translations, including pronunciation and usage context.',
  },
  {
    id: 'default-deck-3',
    topic: 'German Basic Vocabulary',
    description: 'Essential German words for beginners',
    languageFrom: 'German',
    languageTo: 'English',
    amount: 20,
    promptToAiAgent:
      'Please create JSON with basic German vocabulary words and their English translations, including pronunciation and grammar notes.',
  },
  // Add more initial decks here in the future
];

// Initial cards data
export const INITIAL_CARDS: ICardList = [
  // Polish deck words
  {
    id: '1',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Dzień dobry',
    targetWord: 'Good morning',
    pronunciation: '/d͡ʑɛɲ ˈdɔbrɨ/',
    remark: 'Formal greeting used until afternoon',
  },
  {
    id: '2',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Do widzenia',
    targetWord: 'Goodbye',
    pronunciation: '/dɔ viˈd͡zɛɲa/',
    remark: 'Formal farewell, literally "until seeing"',
  },
  {
    id: '3',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Proszę',
    targetWord: 'Please',
    pronunciation: '/ˈprɔʂɛ/',
    remark: 'Also means "you\'re welcome" or "here you go"',
  },
  {
    id: '4',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Dziękuję',
    targetWord: 'Thank you',
    pronunciation: '/d͡ʑɛŋˈkujɛ/',
  },
  {
    id: '5',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Przepraszam',
    targetWord: 'Sorry',
    pronunciation: '/pʂɛˈpraʂam/',
    remark: 'Also used for "excuse me" to get attention',
  },
  {
    id: '6',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Tak',
    targetWord: 'Yes',
    pronunciation: '/tak/',
  },
  {
    id: '7',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Nie',
    targetWord: 'No',
    pronunciation: '/ɲɛ/',
  },
  {
    id: '8',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Cześć',
    targetWord: 'Hi',
    pronunciation: '/t͡ʂɛɕt͡ɕ/',
    remark: 'Informal greeting, also used for goodbye',
  },
  {
    id: '9',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Jak się masz?',
    targetWord: 'How are you?',
    pronunciation: '/jak ɕɛ maʂ/',
    remark: "Informal way to ask about someone's wellbeing",
  },
  {
    id: '10',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Dobranoc',
    targetWord: 'Good night',
    pronunciation: '/dɔˈbranɔt͡s/',
    remark: 'Used when going to sleep or leaving late evening',
  },
  {
    id: '11',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Kocham cię',
    targetWord: 'I love you',
    pronunciation: '/ˈkɔxam t͡ɕɛ/',
    remark: 'Strong expression of love, very intimate',
  },
  {
    id: '12',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Smacznego',
    targetWord: 'Enjoy your meal',
    pronunciation: '/smat͡ʂˈnɛɡɔ/',
    remark: 'Said before eating, equivalent to "bon appétit"',
  },
  {
    id: '13',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Na zdrowie',
    targetWord: 'Cheers',
    pronunciation: '/na ˈzdrɔvjɛ/',
    remark: 'Literally "to your health", also said after sneezing',
  },
  {
    id: '14',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Gdzie jest...?',
    targetWord: 'Where is...?',
    pronunciation: '/ɡd͡ʑɛ jɛst/',
    remark: 'Question phrase for asking location',
  },
  {
    id: '15',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Co słychać?',
    targetWord: "What's up?",
    pronunciation: '/t͡sɔ ˈswɨxat͡ɕ/',
    remark: 'Informal way to ask "what\'s new?" or "how are things?"',
  },
  {
    id: '16',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Wszystkiego najlepszego',
    targetWord: 'All the best',
    pronunciation: '/fʂɨstˈkjɛɡɔ najˈlɛpʂɛɡɔ/',
    remark: 'Used for birthdays, holidays, or general well-wishes',
  },
  {
    id: '17',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Powodzenia',
    targetWord: 'Good luck',
    pronunciation: '/pɔvɔˈd͡zɛɲa/',
    remark: 'Wishing success in endeavors',
  },
  {
    id: '18',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Rozumiem',
    targetWord: 'I understand',
    pronunciation: '/rɔˈzumjɛm/',
  },
  {
    id: '19',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Nie rozumiem',
    targetWord: "I don't understand",
    pronunciation: '/ɲɛ rɔˈzumjɛm/',
    remark: 'Useful phrase when learning the language',
  },
  {
    id: '20',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Dobry wieczór',
    targetWord: 'Good evening',
    pronunciation: '/ˈdɔbrɨ ˈvjɛt͡ʂur/',
    remark: 'Formal greeting used from late afternoon onwards',
  },
  {
    id: '21',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Miło',
    targetWord: 'Nice',
    pronunciation: '/ˈmiwɔ/',
    remark: 'Used to express something pleasant or agreeable',
  },
  {
    id: '22',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Woda',
    targetWord: 'Water',
    pronunciation: '/ˈvɔda/',
  },
  {
    id: '23',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Chleb',
    targetWord: 'Bread',
    pronunciation: '/xlɛp/',
    remark: 'Basic food staple in Polish cuisine',
  },
  {
    id: '24',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Dom',
    targetWord: 'House',
    pronunciation: '/dɔm/',
  },
  {
    id: '25',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Piękny',
    targetWord: 'Beautiful',
    pronunciation: '/ˈpjɛŋknɨ/',
    remark: 'Masculine form, changes with gender and case',
  },
  {
    id: '26',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Mama',
    targetWord: 'Mom',
    pronunciation: '/ˈmama/',
    remark: 'Informal, affectionate term for mother',
  },
  {
    id: '27',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Tata',
    targetWord: 'Dad',
    pronunciation: '/ˈtata/',
    remark: 'Informal, affectionate term for father',
  },
  {
    id: '28',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Kot',
    targetWord: 'Cat',
    pronunciation: '/kɔt/',
  },
  {
    id: '29',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Pies',
    targetWord: 'Dog',
    pronunciation: '/pjɛs/',
  },
  {
    id: '30',
    sourceLanguage: 'Polish',
    targetLanguage: 'English',
    deckId: 'default-deck-1',
    sourceWord: 'Miłość',
    targetWord: 'Love',
    pronunciation: '/ˈmiwɔɕt͡ɕ/',
    remark: 'Abstract noun for the feeling of love',
  },

  // Spanish deck words
  {
    id: '31',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Hola',
    targetWord: 'Hello',
    pronunciation: '/ˈola/',
    remark: 'Most common greeting in Spanish',
  },
  {
    id: '32',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Adiós',
    targetWord: 'Goodbye',
    pronunciation: '/aˈðjos/',
    remark: 'Formal farewell, literally "to God"',
  },
  {
    id: '33',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Por favor',
    targetWord: 'Please',
    pronunciation: '/por faˈβor/',
    remark: 'Polite way to make requests',
  },
  {
    id: '34',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Gracias',
    targetWord: 'Thank you',
    pronunciation: '/ˈɡraθjas/',
    remark: 'Most common way to express gratitude',
  },
  {
    id: '35',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Lo siento',
    targetWord: 'Sorry',
    pronunciation: '/lo ˈsjento/',
    remark: 'Expressing regret or apology',
  },
  {
    id: '36',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Sí',
    targetWord: 'Yes',
    pronunciation: '/si/',
    remark: 'Affirmative response',
  },
  {
    id: '37',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'No',
    targetWord: 'No',
    pronunciation: '/no/',
    remark: 'Negative response, same as English',
  },
  {
    id: '38',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Agua',
    targetWord: 'Water',
    pronunciation: '/ˈaɣwa/',
    remark: 'Essential noun, feminine gender',
  },
  {
    id: '39',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Casa',
    targetWord: 'House',
    pronunciation: '/ˈkasa/',
    remark: 'Basic noun, feminine gender',
  },
  {
    id: '40',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Comida',
    targetWord: 'Food',
    pronunciation: '/koˈmiða/',
    remark: 'General term for food, feminine gender',
  },
  {
    id: '41',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Amor',
    targetWord: 'Love',
    pronunciation: '/aˈmor/',
    remark: 'Noun for love, masculine gender',
  },
  {
    id: '42',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Tiempo',
    targetWord: 'Time',
    pronunciation: '/ˈtjempo/',
    remark: 'Also means weather, masculine gender',
  },
  {
    id: '43',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Bueno',
    targetWord: 'Good',
    pronunciation: '/ˈbweno/',
    remark: 'Masculine form, changes with gender',
  },
  {
    id: '44',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Grande',
    targetWord: 'Big',
    pronunciation: '/ˈɡrande/',
    remark: 'Adjective, same form for masculine and feminine',
  },
  {
    id: '45',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Pequeño',
    targetWord: 'Small',
    pronunciation: '/peˈkeɲo/',
    remark: 'Masculine form, feminine is pequeña',
  },
  {
    id: '46',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Gato',
    targetWord: 'Cat',
    pronunciation: '/ˈɡato/',
    remark: 'Masculine, feminine is gata',
  },
  {
    id: '47',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Perro',
    targetWord: 'Dog',
    pronunciation: '/ˈpero/',
    remark: 'Masculine, feminine is perra',
  },
  {
    id: '48',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Libro',
    targetWord: 'Book',
    pronunciation: '/ˈliβro/',
    remark: 'Masculine gender',
  },
  {
    id: '49',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Escuela',
    targetWord: 'School',
    pronunciation: '/esˈkwela/',
    remark: 'Feminine gender',
  },
  {
    id: '50',
    sourceLanguage: 'Spanish',
    targetLanguage: 'English',
    deckId: 'default-deck-2',
    sourceWord: 'Familia',
    targetWord: 'Family',
    pronunciation: '/faˈmilja/',
    remark: 'Feminine gender, very important concept',
  },

  // German deck words
  {
    id: '51',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Hallo',
    targetWord: 'Hello',
    pronunciation: '/ˈhalo/',
    remark: 'Most common greeting in German',
  },
  {
    id: '52',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Auf Wiedersehen',
    targetWord: 'Goodbye',
    pronunciation: '/aʊf ˈviːdɐˌzeːən/',
    remark: 'Formal farewell, literally "until we see again"',
  },
  {
    id: '53',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Bitte',
    targetWord: 'Please',
    pronunciation: '/ˈbɪtə/',
    remark: 'Also means "you\'re welcome" or "excuse me"',
  },
  {
    id: '54',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Danke',
    targetWord: 'Thank you',
    pronunciation: '/ˈdaŋkə/',
    remark: 'Short form, "Danke schön" is more polite',
  },
  {
    id: '55',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Entschuldigung',
    targetWord: 'Sorry',
    pronunciation: '/ɛntˈʃʊldɪɡʊŋ/',
    remark: 'Also used for "excuse me" to get attention',
  },
  {
    id: '56',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Ja',
    targetWord: 'Yes',
    pronunciation: '/jaː/',
    remark: 'Affirmative response',
  },
  {
    id: '57',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Nein',
    targetWord: 'No',
    pronunciation: '/naɪn/',
    remark: 'Negative response',
  },
  {
    id: '58',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Wasser',
    targetWord: 'Water',
    pronunciation: '/ˈvasɐ/',
    remark: 'Neuter gender: das Wasser',
  },
  {
    id: '59',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Haus',
    targetWord: 'House',
    pronunciation: '/haʊs/',
    remark: 'Neuter gender: das Haus',
  },
  {
    id: '60',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Essen',
    targetWord: 'Food',
    pronunciation: '/ˈɛsən/',
    remark: 'Neuter gender: das Essen (also means "to eat")',
  },
  {
    id: '61',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Liebe',
    targetWord: 'Love',
    pronunciation: '/ˈliːbə/',
    remark: 'Feminine gender: die Liebe',
  },
  {
    id: '62',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Zeit',
    targetWord: 'Time',
    pronunciation: '/tsaɪt/',
    remark: 'Feminine gender: die Zeit',
  },
  {
    id: '63',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Gut',
    targetWord: 'Good',
    pronunciation: '/ɡuːt/',
    remark: 'Adjective, changes with case and gender',
  },
  {
    id: '64',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Groß',
    targetWord: 'Big',
    pronunciation: '/ɡroːs/',
    remark: 'Adjective, changes with case and gender',
  },
  {
    id: '65',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Klein',
    targetWord: 'Small',
    pronunciation: '/klaɪn/',
    remark: 'Adjective, changes with case and gender',
  },
  {
    id: '66',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Katze',
    targetWord: 'Cat',
    pronunciation: '/ˈkatsə/',
    remark: 'Feminine gender: die Katze',
  },
  {
    id: '67',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Hund',
    targetWord: 'Dog',
    pronunciation: '/hʊnt/',
    remark: 'Masculine gender: der Hund',
  },
  {
    id: '68',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Buch',
    targetWord: 'Book',
    pronunciation: '/buːx/',
    remark: 'Neuter gender: das Buch',
  },
  {
    id: '69',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Schule',
    targetWord: 'School',
    pronunciation: '/ˈʃuːlə/',
    remark: 'Feminine gender: die Schule',
  },
  {
    id: '70',
    sourceLanguage: 'German',
    targetLanguage: 'English',
    deckId: 'default-deck-3',
    sourceWord: 'Familie',
    targetWord: 'Family',
    pronunciation: '/faˈmiːljə/',
    remark: 'Feminine gender: die Familie',
  },
];
