// Language mapping for speech synthesis
export const LANGUAGE_MAP: Record<string, string> = {
  polish: 'pl-PL',
  english: 'en-US',
  spanish: 'es-ES',
  french: 'fr-FR',
  german: 'de-DE',
  italian: 'it-IT',
  portuguese: 'pt-PT',
  russian: 'ru-RU',
  chinese: 'zh-CN',
  japanese: 'ja-JP',
  korean: 'ko-KR',
  arabic: 'ar-SA',
  hindi: 'hi-IN',
  dutch: 'nl-NL',
  swedish: 'sv-SE',
  norwegian: 'no-NO',
  danish: 'da-DK',
  finnish: 'fi-FI',
  czech: 'cs-CZ',
  hungarian: 'hu-HU',
  greek: 'el-GR',
  hebrew: 'he-IL',
  turkish: 'tr-TR',
  thai: 'th-TH',
  vietnamese: 'vi-VN',
  indonesian: 'id-ID',
  malay: 'ms-MY',
  filipino: 'fil-PH',
  ukrainian: 'uk-UA',
  bulgarian: 'bg-BG',
  romanian: 'ro-RO',
  croatian: 'hr-HR',
  slovak: 'sk-SK',
  slovenian: 'sl-SI',
  estonian: 'et-EE',
  latvian: 'lv-LV',
  lithuanian: 'lt-LT',
  icelandic: 'is-IS',
  catalan: 'ca-ES',
  basque: 'eu-ES',
  galician: 'gl-ES',
  welsh: 'cy-GB',
  irish: 'ga-IE',
  scottishGaelic: 'gd-GB',
  afrikaans: 'af-ZA',
  swahili: 'sw-KE',
  bengali: 'bn-BD',
  tamil: 'ta-IN',
  telugu: 'te-IN',
  marathi: 'mr-IN',
  gujarati: 'gu-IN',
  kannada: 'kn-IN',
  malayalam: 'ml-IN',
  punjabi: 'pa-IN',
  urdu: 'ur-PK',
  persian: 'fa-IR',
  amharic: 'am-ET',
  yoruba: 'yo-NG',
  hausa: 'ha-NG',
  zulu: 'zu-ZA',
  xhosa: 'xh-ZA',
  belarusian: 'be-BY',
};
// Supported languages list
export const SUPPORTED_LANGUAGES = Object.keys(LANGUAGE_MAP);

export const SUPPORTED_LANGUAGES_NAMES = SUPPORTED_LANGUAGES.map(
  lang => lang.charAt(0).toUpperCase() + lang.slice(1)
).sort();
